### ISSUE TITLE
DES_set_key_checked in blowfish

### ISSUE THREAD

**Issue by jmpews** [jashandeep-sohi/python-blowfish#16]
I encountered a problem about DES_cfb64_encrypt, i use "cipher.encrypt_cfb(data, iv)" but incorrect result. i found that no similar function in cipher.

**Comment by jashandeep-sohi** [comment]
I'm sorry, I don't quite understand the question.

`DES_cf64_encrypt` is presumably the **DES** CFB encryption coroutine from [OpenSSL](https://www.openssl.org/docs/manmaster/crypto/des.html), right? Are you comparing the output of DES & Blowfish? If you are, they will not be the same because they are different ciphers. I think you want [`BF_cfb64_encrypt`](https://www.openssl.org/docs/manmaster/crypto/blowfish.html)

But, CFB in this module is currently implemented as described [here](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_Feedback_.28CFB.29) **without** a shift register. That is, whole previous ciphertext blocks are used as the feedback for the next.

I think OpenSSL implements the shift register logic, making it a true *self-synchronizing byte stream cipher*.

**Comment by jmpews** [comment]
thx,  i understand it wrong before, i rewrite it use openssl. thanks for your answer.
